// <auto-generated />
using System;
using GeoTrees.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoTrees.Api.Migrations
{
    [DbContext(typeof(GeoTreesDbContext))]
    [Migration("20250129200454_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoTrees.Api.Entities.Download", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("GeoTrees.Api.Entities.Plot", b =>
                {
                    b.Property<string>("PlotId")
                        .HasColumnType("text");

                    b.Property<string>("SubPlotId")
                        .HasColumnType("text");

                    b.Property<double?>("AgbChave")
                        .HasColumnType("double precision");

                    b.Property<double?>("AgbChaveCred25")
                        .HasColumnType("double precision");

                    b.Property<double?>("AgbChaveCred975")
                        .HasColumnType("double precision");

                    b.Property<double?>("AgbFeldpausch")
                        .HasColumnType("double precision");

                    b.Property<double?>("AgbFeldpauschCred25")
                        .HasColumnType("double precision");

                    b.Property<double?>("AgbFeldpauschCred975")
                        .HasColumnType("double precision");

                    b.Property<double?>("AgbLocal")
                        .HasColumnType("double precision");

                    b.Property<double?>("AgbLocal975")
                        .HasColumnType("double precision");

                    b.Property<double?>("AgbLocalCred25")
                        .HasColumnType("double precision");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ba")
                        .HasColumnType("double precision");

                    b.Property<string>("BiomassProcessingProtocol")
                        .HasColumnType("text");

                    b.Property<bool>("Confidential")
                        .HasColumnType("boolean");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ForestStatus")
                        .HasColumnType("text");

                    b.Property<double?>("Gsv")
                        .HasColumnType("double precision");

                    b.Property<double?>("HLoreyChave")
                        .HasColumnType("double precision");

                    b.Property<double?>("HLoreyFeldpausch")
                        .HasColumnType("double precision");

                    b.Property<double?>("HLoreyLocal")
                        .HasColumnType("double precision");

                    b.Property<double?>("HMaxChave")
                        .HasColumnType("double precision");

                    b.Property<double?>("HMaxFeldpausch")
                        .HasColumnType("double precision");

                    b.Property<double?>("HMaxLocal")
                        .HasColumnType("double precision");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Institution")
                        .HasColumnType("text");

                    b.Property<double?>("LatCnt")
                        .HasColumnType("double precision");

                    b.Property<double?>("LatNe")
                        .HasColumnType("double precision");

                    b.Property<double?>("LatNw")
                        .HasColumnType("double precision");

                    b.Property<double?>("LatSe")
                        .HasColumnType("double precision");

                    b.Property<double?>("LatSw")
                        .HasColumnType("double precision");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<double?>("LonCnt")
                        .HasColumnType("double precision");

                    b.Property<double?>("LonNe")
                        .HasColumnType("double precision");

                    b.Property<double?>("LonNw")
                        .HasColumnType("double precision");

                    b.Property<double?>("LonSe")
                        .HasColumnType("double precision");

                    b.Property<double?>("LonSw")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinDbh")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ndens")
                        .HasColumnType("double precision");

                    b.Property<string>("Network")
                        .HasColumnType("text");

                    b.Property<string>("OtherMeasurements")
                        .HasColumnType("text");

                    b.Property<string>("PiTeam")
                        .HasColumnType("text");

                    b.Property<double?>("PlotArea")
                        .HasColumnType("double precision");

                    b.Property<string>("PlotShape")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<double?>("SlopeDegree")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("WoodDensity")
                        .HasColumnType("double precision");

                    b.Property<int?>("YearCensus")
                        .HasColumnType("integer");

                    b.Property<int?>("YearEstablished")
                        .HasColumnType("integer");

                    b.HasKey("PlotId", "SubPlotId");

                    b.ToTable("Plots");
                });
#pragma warning restore 612, 618
        }
    }
}
