/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageSlugRouteImport } from './routes/page/$slug'
import { Route as DemoClientRouteImport } from './routes/demo/client'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthMeRouteImport } from './routes/auth/me'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth/confirm-email'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start/server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start/api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api/names'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy.$'
import { Route as AuthedProfileSecurityRouteImport } from './routes/_authed/profile/security'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminTenantsRouteImport } from './routes/_authed/admin/tenants'
import { Route as AuthedAdminRolesRouteImport } from './routes/_authed/admin/roles'
import { Route as AuthedAdminMapLayersRouteImport } from './routes/_authed/admin/map-layers'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start/ssr/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start/ssr/spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start/ssr/full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start/ssr/data-only'
import { Route as AuthedAdminCmsPagesRouteImport } from './routes/_authed/admin/cms/pages'
import { Route as AuthedAdminCmsNavigationRouteImport } from './routes/_authed/admin/cms/navigation'
import { Route as AuthedAdminCmsCommentsRouteImport } from './routes/_authed/admin/cms/comments'
import { Route as AuthedAdminCmsPagesIndexRouteImport } from './routes/_authed/admin/cms/pages/index'
import { Route as AuthedAdminCmsPagesNewRouteImport } from './routes/_authed/admin/cms/pages/new'
import { Route as AuthedAdminCmsPagesIdEditRouteImport } from './routes/_authed/admin/cms/pages/$id/edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/page/$slug',
  path: '/page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClientRoute = DemoClientRouteImport.update({
  id: '/demo/client',
  path: '/demo/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMeRoute = AuthMeRouteImport.update({
  id: '/auth/me',
  path: '/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/auth/confirm-email',
  path: '/auth/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProfileRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileSecurityRoute = AuthedProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedProfileRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminTenantsRoute = AuthedAdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRolesRoute = AuthedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminMapLayersRoute = AuthedAdminMapLayersRouteImport.update({
  id: '/admin/map-layers',
  path: '/admin/map-layers',
  getParentRoute: () => AuthedRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminCmsPagesRoute = AuthedAdminCmsPagesRouteImport.update({
  id: '/admin/cms/pages',
  path: '/admin/cms/pages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminCmsNavigationRoute =
  AuthedAdminCmsNavigationRouteImport.update({
    id: '/admin/cms/navigation',
    path: '/admin/cms/navigation',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminCmsCommentsRoute = AuthedAdminCmsCommentsRouteImport.update({
  id: '/admin/cms/comments',
  path: '/admin/cms/comments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminCmsPagesIndexRoute =
  AuthedAdminCmsPagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAdminCmsPagesRoute,
  } as any)
const AuthedAdminCmsPagesNewRoute = AuthedAdminCmsPagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedAdminCmsPagesRoute,
} as any)
const AuthedAdminCmsPagesIdEditRoute =
  AuthedAdminCmsPagesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthedAdminCmsPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/profile': typeof AuthedProfileRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/demo/client': typeof DemoClientRoute
  '/page/$slug': typeof PageSlugRoute
  '/admin/map-layers': typeof AuthedAdminMapLayersRoute
  '/admin/roles': typeof AuthedAdminRolesRoute
  '/admin/tenants': typeof AuthedAdminTenantsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/profile/security': typeof AuthedProfileSecurityRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/admin/cms/comments': typeof AuthedAdminCmsCommentsRoute
  '/admin/cms/navigation': typeof AuthedAdminCmsNavigationRoute
  '/admin/cms/pages': typeof AuthedAdminCmsPagesRouteWithChildren
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/admin/cms/pages/new': typeof AuthedAdminCmsPagesNewRoute
  '/admin/cms/pages/': typeof AuthedAdminCmsPagesIndexRoute
  '/admin/cms/pages/$id/edit': typeof AuthedAdminCmsPagesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/demo/client': typeof DemoClientRoute
  '/page/$slug': typeof PageSlugRoute
  '/admin/map-layers': typeof AuthedAdminMapLayersRoute
  '/admin/roles': typeof AuthedAdminRolesRoute
  '/admin/tenants': typeof AuthedAdminTenantsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/profile/security': typeof AuthedProfileSecurityRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/cms/comments': typeof AuthedAdminCmsCommentsRoute
  '/admin/cms/navigation': typeof AuthedAdminCmsNavigationRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/admin/cms/pages/new': typeof AuthedAdminCmsPagesNewRoute
  '/admin/cms/pages': typeof AuthedAdminCmsPagesIndexRoute
  '/admin/cms/pages/$id/edit': typeof AuthedAdminCmsPagesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/profile': typeof AuthedProfileRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/demo/client': typeof DemoClientRoute
  '/page/$slug': typeof PageSlugRoute
  '/_authed/admin/map-layers': typeof AuthedAdminMapLayersRoute
  '/_authed/admin/roles': typeof AuthedAdminRolesRoute
  '/_authed/admin/tenants': typeof AuthedAdminTenantsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/profile/security': typeof AuthedProfileSecurityRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/admin/cms/comments': typeof AuthedAdminCmsCommentsRoute
  '/_authed/admin/cms/navigation': typeof AuthedAdminCmsNavigationRoute
  '/_authed/admin/cms/pages': typeof AuthedAdminCmsPagesRouteWithChildren
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/_authed/admin/cms/pages/new': typeof AuthedAdminCmsPagesNewRoute
  '/_authed/admin/cms/pages/': typeof AuthedAdminCmsPagesIndexRoute
  '/_authed/admin/cms/pages/$id/edit': typeof AuthedAdminCmsPagesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/profile'
    | '/dashboard'
    | '/settings'
    | '/api/health'
    | '/auth/callback'
    | '/auth/confirm-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/me'
    | '/auth/register'
    | '/auth/reset-password'
    | '/demo/client'
    | '/page/$slug'
    | '/admin/map-layers'
    | '/admin/roles'
    | '/admin/tenants'
    | '/admin/users'
    | '/profile/security'
    | '/api/proxy/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/profile/'
    | '/admin/cms/comments'
    | '/admin/cms/navigation'
    | '/admin/cms/pages'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/admin/cms/pages/new'
    | '/admin/cms/pages/'
    | '/admin/cms/pages/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/profile'
    | '/dashboard'
    | '/settings'
    | '/api/health'
    | '/auth/callback'
    | '/auth/confirm-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/me'
    | '/auth/register'
    | '/auth/reset-password'
    | '/demo/client'
    | '/page/$slug'
    | '/admin/map-layers'
    | '/admin/roles'
    | '/admin/tenants'
    | '/admin/users'
    | '/profile/security'
    | '/api/proxy/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/cms/comments'
    | '/admin/cms/navigation'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/admin/cms/pages/new'
    | '/admin/cms/pages'
    | '/admin/cms/pages/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/map'
    | '/profile'
    | '/_authed/dashboard'
    | '/_authed/profile'
    | '/_authed/settings'
    | '/api/health'
    | '/auth/callback'
    | '/auth/confirm-email'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/me'
    | '/auth/register'
    | '/auth/reset-password'
    | '/demo/client'
    | '/page/$slug'
    | '/_authed/admin/map-layers'
    | '/_authed/admin/roles'
    | '/_authed/admin/tenants'
    | '/_authed/admin/users'
    | '/_authed/profile/security'
    | '/api/proxy/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_authed/profile/'
    | '/_authed/admin/cms/comments'
    | '/_authed/admin/cms/navigation'
    | '/_authed/admin/cms/pages'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/_authed/admin/cms/pages/new'
    | '/_authed/admin/cms/pages/'
    | '/_authed/admin/cms/pages/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthMeRoute: typeof AuthMeRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  DemoClientRoute: typeof DemoClientRoute
  PageSlugRoute: typeof PageSlugRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$slug': {
      id: '/page/$slug'
      path: '/page/$slug'
      fullPath: '/page/$slug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/client': {
      id: '/demo/client'
      path: '/demo/client'
      fullPath: '/demo/client'
      preLoaderRoute: typeof DemoClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/me': {
      id: '/auth/me'
      path: '/auth/me'
      fullPath: '/auth/me'
      preLoaderRoute: typeof AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/auth/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedProfileRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile/security': {
      id: '/_authed/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AuthedProfileSecurityRouteImport
      parentRoute: typeof AuthedProfileRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/tenants': {
      id: '/_authed/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthedAdminTenantsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/roles': {
      id: '/_authed/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthedAdminRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/map-layers': {
      id: '/_authed/admin/map-layers'
      path: '/admin/map-layers'
      fullPath: '/admin/map-layers'
      preLoaderRoute: typeof AuthedAdminMapLayersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/cms/pages': {
      id: '/_authed/admin/cms/pages'
      path: '/admin/cms/pages'
      fullPath: '/admin/cms/pages'
      preLoaderRoute: typeof AuthedAdminCmsPagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/cms/navigation': {
      id: '/_authed/admin/cms/navigation'
      path: '/admin/cms/navigation'
      fullPath: '/admin/cms/navigation'
      preLoaderRoute: typeof AuthedAdminCmsNavigationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/cms/comments': {
      id: '/_authed/admin/cms/comments'
      path: '/admin/cms/comments'
      fullPath: '/admin/cms/comments'
      preLoaderRoute: typeof AuthedAdminCmsCommentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/cms/pages/': {
      id: '/_authed/admin/cms/pages/'
      path: '/'
      fullPath: '/admin/cms/pages/'
      preLoaderRoute: typeof AuthedAdminCmsPagesIndexRouteImport
      parentRoute: typeof AuthedAdminCmsPagesRoute
    }
    '/_authed/admin/cms/pages/new': {
      id: '/_authed/admin/cms/pages/new'
      path: '/new'
      fullPath: '/admin/cms/pages/new'
      preLoaderRoute: typeof AuthedAdminCmsPagesNewRouteImport
      parentRoute: typeof AuthedAdminCmsPagesRoute
    }
    '/_authed/admin/cms/pages/$id/edit': {
      id: '/_authed/admin/cms/pages/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/cms/pages/$id/edit'
      preLoaderRoute: typeof AuthedAdminCmsPagesIdEditRouteImport
      parentRoute: typeof AuthedAdminCmsPagesRoute
    }
  }
}

interface AuthedProfileRouteChildren {
  AuthedProfileSecurityRoute: typeof AuthedProfileSecurityRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedProfileRouteChildren: AuthedProfileRouteChildren = {
  AuthedProfileSecurityRoute: AuthedProfileSecurityRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedProfileRouteWithChildren = AuthedProfileRoute._addFileChildren(
  AuthedProfileRouteChildren,
)

interface AuthedAdminCmsPagesRouteChildren {
  AuthedAdminCmsPagesNewRoute: typeof AuthedAdminCmsPagesNewRoute
  AuthedAdminCmsPagesIndexRoute: typeof AuthedAdminCmsPagesIndexRoute
  AuthedAdminCmsPagesIdEditRoute: typeof AuthedAdminCmsPagesIdEditRoute
}

const AuthedAdminCmsPagesRouteChildren: AuthedAdminCmsPagesRouteChildren = {
  AuthedAdminCmsPagesNewRoute: AuthedAdminCmsPagesNewRoute,
  AuthedAdminCmsPagesIndexRoute: AuthedAdminCmsPagesIndexRoute,
  AuthedAdminCmsPagesIdEditRoute: AuthedAdminCmsPagesIdEditRoute,
}

const AuthedAdminCmsPagesRouteWithChildren =
  AuthedAdminCmsPagesRoute._addFileChildren(AuthedAdminCmsPagesRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProfileRoute: typeof AuthedProfileRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedAdminMapLayersRoute: typeof AuthedAdminMapLayersRoute
  AuthedAdminRolesRoute: typeof AuthedAdminRolesRoute
  AuthedAdminTenantsRoute: typeof AuthedAdminTenantsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminCmsCommentsRoute: typeof AuthedAdminCmsCommentsRoute
  AuthedAdminCmsNavigationRoute: typeof AuthedAdminCmsNavigationRoute
  AuthedAdminCmsPagesRoute: typeof AuthedAdminCmsPagesRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProfileRoute: AuthedProfileRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedAdminMapLayersRoute: AuthedAdminMapLayersRoute,
  AuthedAdminRolesRoute: AuthedAdminRolesRoute,
  AuthedAdminTenantsRoute: AuthedAdminTenantsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminCmsCommentsRoute: AuthedAdminCmsCommentsRoute,
  AuthedAdminCmsNavigationRoute: AuthedAdminCmsNavigationRoute,
  AuthedAdminCmsPagesRoute: AuthedAdminCmsPagesRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthMeRoute: AuthMeRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  DemoClientRoute: DemoClientRoute,
  PageSlugRoute: PageSlugRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
