// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zApplicationAuthConfigurationDto = z.object({
    grantedPolicies: z.optional(z.union([
        z.record(z.string(), z.boolean()),
        z.null()
    ]))
});

export type ApplicationAuthConfigurationDtoZodType = z.infer<typeof zApplicationAuthConfigurationDto>;

export const zApplicationFeatureConfigurationDto = z.object({
    values: z.optional(z.union([
        z.record(z.string(), z.union([
            z.string(),
            z.null()
        ])),
        z.null()
    ]))
});

export type ApplicationFeatureConfigurationDtoZodType = z.infer<typeof zApplicationFeatureConfigurationDto>;

export const zApplicationGlobalFeatureConfigurationDto = z.object({
    enabledFeatures: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ]))
});

export type ApplicationGlobalFeatureConfigurationDtoZodType = z.infer<typeof zApplicationGlobalFeatureConfigurationDto>;

export const zApplicationLocalizationResourceDto = z.object({
    texts: z.optional(z.union([
        z.record(z.string(), z.string()),
        z.null()
    ])),
    baseResources: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ]))
});

export type ApplicationLocalizationResourceDtoZodType = z.infer<typeof zApplicationLocalizationResourceDto>;

export const zApplicationSettingConfigurationDto = z.object({
    values: z.optional(z.union([
        z.record(z.string(), z.union([
            z.string(),
            z.null()
        ])),
        z.null()
    ]))
});

export type ApplicationSettingConfigurationDtoZodType = z.infer<typeof zApplicationSettingConfigurationDto>;

export const zBookType = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5),
    z.literal(6),
    z.literal(7),
    z.literal(8)
]);

export type BookTypeZodType = z.infer<typeof zBookType>;

export const zBookDto = z.object({
    id: z.optional(z.uuid()),
    creationTime: z.optional(z.iso.datetime()),
    creatorId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    lastModificationTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    lastModifierId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    type: z.optional(zBookType),
    publishDate: z.optional(z.iso.datetime()),
    price: z.optional(z.number())
});

export type BookDtoZodType = z.infer<typeof zBookDto>;

export const zChangePasswordInput = z.object({
    currentPassword: z.optional(z.union([
        z.string().min(0).max(128),
        z.null()
    ])),
    newPassword: z.string().min(0).max(128)
});

export type ChangePasswordInputZodType = z.infer<typeof zChangePasswordInput>;

export const zClockDto = z.object({
    kind: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type ClockDtoZodType = z.infer<typeof zClockDto>;

export const zCmsKitPageDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    id: z.optional(z.uuid()),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    slug: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    layoutName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    content: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    script: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    style: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type CmsKitPageDtoZodType = z.infer<typeof zCmsKitPageDto>;

export const zCreatePageInputDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    title: z.string().min(1).max(256),
    slug: z.string().min(1).max(256),
    layoutName: z.optional(z.union([
        z.string().max(256),
        z.null()
    ])),
    content: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    script: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    style: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ]))
});

export type CreatePageInputDtoZodType = z.infer<typeof zCreatePageInputDto>;

export const zCreateUpdateBookDto = z.object({
    name: z.string().min(0).max(128),
    type: zBookType,
    publishDate: z.iso.date(),
    price: z.number()
});

export type CreateUpdateBookDtoZodType = z.infer<typeof zCreateUpdateBookDto>;

export const zCurrentTenantDto = z.object({
    id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isAvailable: z.optional(z.boolean())
});

export type CurrentTenantDtoZodType = z.infer<typeof zCurrentTenantDto>;

export const zCurrentUserDto = z.object({
    isAuthenticated: z.optional(z.boolean()),
    id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    tenantId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    impersonatorUserId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    impersonatorTenantId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    impersonatorUserName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    impersonatorTenantName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    userName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    surName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    emailVerified: z.optional(z.boolean()),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phoneNumberVerified: z.optional(z.boolean()),
    roles: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    sessionId: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type CurrentUserDtoZodType = z.infer<typeof zCurrentUserDto>;

export const zDateTimeFormatDto = z.object({
    calendarAlgorithmType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    dateTimeFormatLong: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    shortDatePattern: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    fullDateTimePattern: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    dateSeparator: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    shortTimePattern: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    longTimePattern: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type DateTimeFormatDtoZodType = z.infer<typeof zDateTimeFormatDto>;

export const zCurrentCultureDto = z.object({
    displayName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    englishName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    threeLetterIsoLanguageName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    twoLetterIsoLanguageName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isRightToLeft: z.optional(z.boolean()),
    cultureName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    nativeName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    dateTimeFormat: z.optional(zDateTimeFormatDto)
});

export type CurrentCultureDtoZodType = z.infer<typeof zCurrentCultureDto>;

export const zApplicationLocalizationDto = z.object({
    resources: z.optional(z.union([
        z.record(z.string(), zApplicationLocalizationResourceDto),
        z.null()
    ])),
    currentCulture: z.optional(zCurrentCultureDto)
});

export type ApplicationLocalizationDtoZodType = z.infer<typeof zApplicationLocalizationDto>;

export const zEmailSettingsDto = z.object({
    smtpHost: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    smtpPort: z.optional(z.int()),
    smtpUserName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    smtpPassword: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    smtpDomain: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    smtpEnableSsl: z.optional(z.boolean()),
    smtpUseDefaultCredentials: z.optional(z.boolean()),
    defaultFromAddress: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    defaultFromDisplayName: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type EmailSettingsDtoZodType = z.infer<typeof zEmailSettingsDto>;

export const zExtensionEnumFieldDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    value: z.optional(z.unknown())
});

export type ExtensionEnumFieldDtoZodType = z.infer<typeof zExtensionEnumFieldDto>;

export const zExtensionEnumDto = z.object({
    fields: z.optional(z.union([
        z.array(zExtensionEnumFieldDto),
        z.null()
    ])),
    localizationResource: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type ExtensionEnumDtoZodType = z.infer<typeof zExtensionEnumDto>;

export const zExtensionPropertyApiCreateDto = z.object({
    isAvailable: z.optional(z.boolean())
});

export type ExtensionPropertyApiCreateDtoZodType = z.infer<typeof zExtensionPropertyApiCreateDto>;

export const zExtensionPropertyApiGetDto = z.object({
    isAvailable: z.optional(z.boolean())
});

export type ExtensionPropertyApiGetDtoZodType = z.infer<typeof zExtensionPropertyApiGetDto>;

export const zExtensionPropertyApiUpdateDto = z.object({
    isAvailable: z.optional(z.boolean())
});

export type ExtensionPropertyApiUpdateDtoZodType = z.infer<typeof zExtensionPropertyApiUpdateDto>;

export const zExtensionPropertyApiDto = z.object({
    onGet: z.optional(zExtensionPropertyApiGetDto),
    onCreate: z.optional(zExtensionPropertyApiCreateDto),
    onUpdate: z.optional(zExtensionPropertyApiUpdateDto)
});

export type ExtensionPropertyApiDtoZodType = z.infer<typeof zExtensionPropertyApiDto>;

export const zExtensionPropertyAttributeDto = z.object({
    typeSimple: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    config: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ]))
});

export type ExtensionPropertyAttributeDtoZodType = z.infer<typeof zExtensionPropertyAttributeDto>;

export const zExtensionPropertyFeaturePolicyDto = z.object({
    features: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    requiresAll: z.optional(z.boolean())
});

export type ExtensionPropertyFeaturePolicyDtoZodType = z.infer<typeof zExtensionPropertyFeaturePolicyDto>;

export const zExtensionPropertyGlobalFeaturePolicyDto = z.object({
    features: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    requiresAll: z.optional(z.boolean())
});

export type ExtensionPropertyGlobalFeaturePolicyDtoZodType = z.infer<typeof zExtensionPropertyGlobalFeaturePolicyDto>;

export const zExtensionPropertyPermissionPolicyDto = z.object({
    permissionNames: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    requiresAll: z.optional(z.boolean())
});

export type ExtensionPropertyPermissionPolicyDtoZodType = z.infer<typeof zExtensionPropertyPermissionPolicyDto>;

export const zExtensionPropertyPolicyDto = z.object({
    globalFeatures: z.optional(zExtensionPropertyGlobalFeaturePolicyDto),
    features: z.optional(zExtensionPropertyFeaturePolicyDto),
    permissions: z.optional(zExtensionPropertyPermissionPolicyDto)
});

export type ExtensionPropertyPolicyDtoZodType = z.infer<typeof zExtensionPropertyPolicyDto>;

export const zExtensionPropertyUiFormDto = z.object({
    isVisible: z.optional(z.boolean())
});

export type ExtensionPropertyUiFormDtoZodType = z.infer<typeof zExtensionPropertyUiFormDto>;

export const zExtensionPropertyUiLookupDto = z.object({
    url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    resultListPropertyName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayPropertyName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    valuePropertyName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    filterParamName: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type ExtensionPropertyUiLookupDtoZodType = z.infer<typeof zExtensionPropertyUiLookupDto>;

export const zExtensionPropertyUiTableDto = z.object({
    isVisible: z.optional(z.boolean())
});

export type ExtensionPropertyUiTableDtoZodType = z.infer<typeof zExtensionPropertyUiTableDto>;

export const zExtensionPropertyUiDto = z.object({
    onTable: z.optional(zExtensionPropertyUiTableDto),
    onCreateForm: z.optional(zExtensionPropertyUiFormDto),
    onEditForm: z.optional(zExtensionPropertyUiFormDto),
    lookup: z.optional(zExtensionPropertyUiLookupDto)
});

export type ExtensionPropertyUiDtoZodType = z.infer<typeof zExtensionPropertyUiDto>;

export const zFeatureProviderDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    key: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type FeatureProviderDtoZodType = z.infer<typeof zFeatureProviderDto>;

export const zFindTenantResultDto = z.object({
    success: z.optional(z.boolean()),
    tenantId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    normalizedName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isActive: z.optional(z.boolean())
});

export type FindTenantResultDtoZodType = z.infer<typeof zFindTenantResultDto>;

export const zIValueValidator = z.object({
    name: z.optional(z.union([
        z.string().readonly(),
        z.null()
    ]).readonly()),
    properties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly())
});

export type IValueValidatorZodType = z.infer<typeof zIValueValidator>;

export const zIStringValueType = z.object({
    name: z.optional(z.union([
        z.string().readonly(),
        z.null()
    ]).readonly()),
    properties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    validator: z.optional(zIValueValidator)
});

export type IStringValueTypeZodType = z.infer<typeof zIStringValueType>;

export const zFeatureDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    value: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    provider: z.optional(zFeatureProviderDto),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    valueType: z.optional(zIStringValueType),
    depth: z.optional(z.int()),
    parentName: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type FeatureDtoZodType = z.infer<typeof zFeatureDto>;

export const zFeatureGroupDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    features: z.optional(z.union([
        z.array(zFeatureDto),
        z.null()
    ]))
});

export type FeatureGroupDtoZodType = z.infer<typeof zFeatureGroupDto>;

export const zGetFeatureListResultDto = z.object({
    groups: z.optional(z.union([
        z.array(zFeatureGroupDto),
        z.null()
    ]))
});

export type GetFeatureListResultDtoZodType = z.infer<typeof zGetFeatureListResultDto>;

export const zIanaTimeZone = z.object({
    timeZoneName: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type IanaTimeZoneZodType = z.infer<typeof zIanaTimeZone>;

export const zIdentityRoleCreateDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    name: z.string().min(0).max(256),
    isDefault: z.optional(z.boolean()),
    isPublic: z.optional(z.boolean())
});

export type IdentityRoleCreateDtoZodType = z.infer<typeof zIdentityRoleCreateDto>;

export const zIdentityRoleDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    id: z.optional(z.uuid()),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isDefault: z.optional(z.boolean()),
    isStatic: z.optional(z.boolean()),
    isPublic: z.optional(z.boolean()),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    creationTime: z.optional(z.iso.datetime())
});

export type IdentityRoleDtoZodType = z.infer<typeof zIdentityRoleDto>;

export const zIdentityRoleUpdateDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    name: z.string().min(0).max(256),
    isDefault: z.optional(z.boolean()),
    isPublic: z.optional(z.boolean()),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type IdentityRoleUpdateDtoZodType = z.infer<typeof zIdentityRoleUpdateDto>;

export const zIdentityUserCreateDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    userName: z.string().min(0).max(256),
    name: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    email: z.email().min(0).max(256),
    phoneNumber: z.optional(z.union([
        z.string().min(0).max(16),
        z.null()
    ])),
    isActive: z.optional(z.boolean()),
    lockoutEnabled: z.optional(z.boolean()),
    roleNames: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    password: z.string().min(0).max(128)
});

export type IdentityUserCreateDtoZodType = z.infer<typeof zIdentityUserCreateDto>;

export const zIdentityUserDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    id: z.optional(z.uuid()),
    creationTime: z.optional(z.iso.datetime()),
    creatorId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    lastModificationTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    lastModifierId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    isDeleted: z.optional(z.boolean()),
    deleterId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    deletionTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    tenantId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    userName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    emailConfirmed: z.optional(z.boolean()),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phoneNumberConfirmed: z.optional(z.boolean()),
    isActive: z.optional(z.boolean()),
    lockoutEnabled: z.optional(z.boolean()),
    accessFailedCount: z.optional(z.int()),
    lockoutEnd: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    entityVersion: z.optional(z.int()),
    lastPasswordChangeTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
});

export type IdentityUserDtoZodType = z.infer<typeof zIdentityUserDto>;

export const zIdentityUserUpdateDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    userName: z.string().min(0).max(256),
    name: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    email: z.email().min(0).max(256),
    phoneNumber: z.optional(z.union([
        z.string().min(0).max(16),
        z.null()
    ])),
    isActive: z.optional(z.boolean()),
    lockoutEnabled: z.optional(z.boolean()),
    roleNames: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    password: z.optional(z.union([
        z.string().min(0).max(128),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type IdentityUserUpdateDtoZodType = z.infer<typeof zIdentityUserUpdateDto>;

export const zIdentityUserUpdateRolesDto = z.object({
    roleNames: z.array(z.string())
});

export type IdentityUserUpdateRolesDtoZodType = z.infer<typeof zIdentityUserUpdateRolesDto>;

export const zLanguageInfo = z.object({
    cultureName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    uiCultureName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    twoLetterISOLanguageName: z.optional(z.union([
        z.string().readonly(),
        z.null()
    ]).readonly())
});

export type LanguageInfoZodType = z.infer<typeof zLanguageInfo>;

export const zListResultDto_IdentityRoleDto_ = z.object({
    items: z.optional(z.union([
        z.array(zIdentityRoleDto),
        z.null()
    ]))
});

export type ListResultDto_IdentityRoleDto_ZodType = z.infer<typeof zListResultDto_IdentityRoleDto_>;

export const zLocalizableStringDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    resource: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type LocalizableStringDtoZodType = z.infer<typeof zLocalizableStringDto>;

export const zExtensionPropertyDto = z.object({
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    typeSimple: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayName: z.optional(zLocalizableStringDto),
    api: z.optional(zExtensionPropertyApiDto),
    ui: z.optional(zExtensionPropertyUiDto),
    policy: z.optional(zExtensionPropertyPolicyDto),
    attributes: z.optional(z.union([
        z.array(zExtensionPropertyAttributeDto),
        z.null()
    ])),
    configuration: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ])),
    defaultValue: z.optional(z.unknown())
});

export type ExtensionPropertyDtoZodType = z.infer<typeof zExtensionPropertyDto>;

export const zEntityExtensionDto = z.object({
    properties: z.optional(z.union([
        z.record(z.string(), zExtensionPropertyDto),
        z.null()
    ])),
    configuration: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ]))
});

export type EntityExtensionDtoZodType = z.infer<typeof zEntityExtensionDto>;

export const zLoginResultType = z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5)
]);

export type LoginResultTypeZodType = z.infer<typeof zLoginResultType>;

export const zAbpLoginResult = z.object({
    result: z.optional(zLoginResultType),
    description: z.optional(z.union([
        z.string().readonly(),
        z.null()
    ]).readonly())
});

export type AbpLoginResultZodType = z.infer<typeof zAbpLoginResult>;

export const zMethodParameterApiDescriptionModel = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    typeAsString: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    typeSimple: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isOptional: z.optional(z.boolean()),
    defaultValue: z.optional(z.unknown())
});

export type MethodParameterApiDescriptionModelZodType = z.infer<typeof zMethodParameterApiDescriptionModel>;

export const zModuleExtensionDto = z.object({
    entities: z.optional(z.union([
        z.record(z.string(), zEntityExtensionDto),
        z.null()
    ])),
    configuration: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ]))
});

export type ModuleExtensionDtoZodType = z.infer<typeof zModuleExtensionDto>;

export const zMultiTenancyInfoDto = z.object({
    isEnabled: z.optional(z.boolean())
});

export type MultiTenancyInfoDtoZodType = z.infer<typeof zMultiTenancyInfoDto>;

export const zNameValue = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    value: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type NameValueZodType = z.infer<typeof zNameValue>;

export const zApplicationLocalizationConfigurationDto = z.object({
    values: z.optional(z.union([
        z.record(z.string(), z.record(z.string(), z.string())),
        z.null()
    ])),
    resources: z.optional(z.union([
        z.record(z.string(), zApplicationLocalizationResourceDto),
        z.null()
    ])),
    languages: z.optional(z.union([
        z.array(zLanguageInfo),
        z.null()
    ])),
    currentCulture: z.optional(zCurrentCultureDto),
    defaultResourceName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    languagesMap: z.optional(z.union([
        z.record(z.string(), z.array(zNameValue)),
        z.null()
    ])),
    languageFilesMap: z.optional(z.union([
        z.record(z.string(), z.array(zNameValue)),
        z.null()
    ]))
});

export type ApplicationLocalizationConfigurationDtoZodType = z.infer<typeof zApplicationLocalizationConfigurationDto>;

export const zObjectExtensionsDto = z.object({
    modules: z.optional(z.union([
        z.record(z.string(), zModuleExtensionDto),
        z.null()
    ])),
    enums: z.optional(z.union([
        z.record(z.string(), zExtensionEnumDto),
        z.null()
    ]))
});

export type ObjectExtensionsDtoZodType = z.infer<typeof zObjectExtensionsDto>;

export const zPageDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    id: z.optional(z.uuid()),
    creationTime: z.optional(z.iso.datetime()),
    creatorId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    lastModificationTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    lastModifierId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    slug: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    layoutName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    content: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    script: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    style: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isHomePage: z.optional(z.boolean()),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type PageDtoZodType = z.infer<typeof zPageDto>;

export const zPagedResultDto_BookDto_ = z.object({
    items: z.optional(z.union([
        z.array(zBookDto),
        z.null()
    ])),
    totalCount: z.optional(z.coerce.bigint())
});

export type PagedResultDto_BookDto_ZodType = z.infer<typeof zPagedResultDto_BookDto_>;

export const zPagedResultDto_IdentityRoleDto_ = z.object({
    items: z.optional(z.union([
        z.array(zIdentityRoleDto),
        z.null()
    ])),
    totalCount: z.optional(z.coerce.bigint())
});

export type PagedResultDto_IdentityRoleDto_ZodType = z.infer<typeof zPagedResultDto_IdentityRoleDto_>;

export const zPagedResultDto_IdentityUserDto_ = z.object({
    items: z.optional(z.union([
        z.array(zIdentityUserDto),
        z.null()
    ])),
    totalCount: z.optional(z.coerce.bigint())
});

export type PagedResultDto_IdentityUserDto_ZodType = z.infer<typeof zPagedResultDto_IdentityUserDto_>;

export const zPagedResultDto_PageDto_ = z.object({
    items: z.optional(z.union([
        z.array(zPageDto),
        z.null()
    ])),
    totalCount: z.optional(z.coerce.bigint())
});

export type PagedResultDto_PageDto_ZodType = z.infer<typeof zPagedResultDto_PageDto_>;

export const zParameterApiDescriptionModel = z.object({
    nameOnMethod: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    jsonName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    typeSimple: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isOptional: z.optional(z.boolean()),
    defaultValue: z.optional(z.unknown()),
    constraintTypes: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    bindingSourceId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    descriptorName: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type ParameterApiDescriptionModelZodType = z.infer<typeof zParameterApiDescriptionModel>;

export const zProfileDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    userName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isExternal: z.optional(z.boolean()),
    hasPassword: z.optional(z.boolean()),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type ProfileDtoZodType = z.infer<typeof zProfileDto>;

export const zPropertyApiDescriptionModel = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    jsonName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    typeSimple: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isRequired: z.optional(z.boolean()),
    minLength: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    maxLength: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    minimum: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    maximum: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    regex: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isNullable: z.optional(z.boolean())
});

export type PropertyApiDescriptionModelZodType = z.infer<typeof zPropertyApiDescriptionModel>;

export const zProviderInfoDto = z.object({
    providerName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    providerKey: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type ProviderInfoDtoZodType = z.infer<typeof zProviderInfoDto>;

export const zPermissionGrantInfoDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    parentName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isGranted: z.optional(z.boolean()),
    allowedProviders: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    grantedProviders: z.optional(z.union([
        z.array(zProviderInfoDto),
        z.null()
    ]))
});

export type PermissionGrantInfoDtoZodType = z.infer<typeof zPermissionGrantInfoDto>;

export const zPermissionGroupDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayNameKey: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayNameResource: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    permissions: z.optional(z.union([
        z.array(zPermissionGrantInfoDto),
        z.null()
    ]))
});

export type PermissionGroupDtoZodType = z.infer<typeof zPermissionGroupDto>;

export const zGetPermissionListResultDto = z.object({
    entityDisplayName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    groups: z.optional(z.union([
        z.array(zPermissionGroupDto),
        z.null()
    ]))
});

export type GetPermissionListResultDtoZodType = z.infer<typeof zGetPermissionListResultDto>;

export const zRegisterDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    userName: z.string().min(0).max(256),
    emailAddress: z.email().min(0).max(256),
    password: z.string().min(0).max(128),
    appName: z.string().min(1)
});

export type RegisterDtoZodType = z.infer<typeof zRegisterDto>;

export const zRemoteServiceValidationErrorInfo = z.object({
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    members: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ]))
});

export type RemoteServiceValidationErrorInfoZodType = z.infer<typeof zRemoteServiceValidationErrorInfo>;

export const zRemoteServiceErrorInfo = z.object({
    code: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    details: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ])),
    validationErrors: z.optional(z.union([
        z.array(zRemoteServiceValidationErrorInfo),
        z.null()
    ]))
});

export type RemoteServiceErrorInfoZodType = z.infer<typeof zRemoteServiceErrorInfo>;

export const zRemoteServiceErrorResponse = z.object({
    error: z.optional(zRemoteServiceErrorInfo)
});

export type RemoteServiceErrorResponseZodType = z.infer<typeof zRemoteServiceErrorResponse>;

export const zResetPasswordDto = z.object({
    userId: z.optional(z.uuid()),
    resetToken: z.string().min(1),
    password: z.string().min(1)
});

export type ResetPasswordDtoZodType = z.infer<typeof zResetPasswordDto>;

export const zReturnValueApiDescriptionModel = z.object({
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    typeSimple: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type ReturnValueApiDescriptionModelZodType = z.infer<typeof zReturnValueApiDescriptionModel>;

export const zActionApiDescriptionModel = z.object({
    uniqueName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    httpMethod: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    supportedVersions: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    parametersOnMethod: z.optional(z.union([
        z.array(zMethodParameterApiDescriptionModel),
        z.null()
    ])),
    parameters: z.optional(z.union([
        z.array(zParameterApiDescriptionModel),
        z.null()
    ])),
    returnValue: z.optional(zReturnValueApiDescriptionModel),
    allowAnonymous: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    implementFrom: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type ActionApiDescriptionModelZodType = z.infer<typeof zActionApiDescriptionModel>;

export const zInterfaceMethodApiDescriptionModel = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    parametersOnMethod: z.optional(z.union([
        z.array(zMethodParameterApiDescriptionModel),
        z.null()
    ])),
    returnValue: z.optional(zReturnValueApiDescriptionModel)
});

export type InterfaceMethodApiDescriptionModelZodType = z.infer<typeof zInterfaceMethodApiDescriptionModel>;

export const zControllerInterfaceApiDescriptionModel = z.object({
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    methods: z.optional(z.union([
        z.array(zInterfaceMethodApiDescriptionModel),
        z.null()
    ]))
});

export type ControllerInterfaceApiDescriptionModelZodType = z.infer<typeof zControllerInterfaceApiDescriptionModel>;

export const zControllerApiDescriptionModel = z.object({
    controllerName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    controllerGroupName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isRemoteService: z.optional(z.boolean()),
    isIntegrationService: z.optional(z.boolean()),
    apiVersion: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    interfaces: z.optional(z.union([
        z.array(zControllerInterfaceApiDescriptionModel),
        z.null()
    ])),
    actions: z.optional(z.union([
        z.record(z.string(), zActionApiDescriptionModel),
        z.null()
    ]))
});

export type ControllerApiDescriptionModelZodType = z.infer<typeof zControllerApiDescriptionModel>;

export const zModuleApiDescriptionModel = z.object({
    rootPath: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    remoteServiceName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    controllers: z.optional(z.union([
        z.record(z.string(), zControllerApiDescriptionModel),
        z.null()
    ]))
});

export type ModuleApiDescriptionModelZodType = z.infer<typeof zModuleApiDescriptionModel>;

export const zSendPasswordResetCodeDto = z.object({
    email: z.email().min(0).max(256),
    appName: z.string().min(1),
    returnUrl: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    returnUrlHash: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type SendPasswordResetCodeDtoZodType = z.infer<typeof zSendPasswordResetCodeDto>;

export const zSendTestEmailInput = z.object({
    senderEmailAddress: z.string().min(1),
    targetEmailAddress: z.string().min(1),
    subject: z.string().min(1),
    body: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type SendTestEmailInputZodType = z.infer<typeof zSendTestEmailInput>;

export const zTenantCreateDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    name: z.string().min(0).max(64),
    adminEmailAddress: z.email().min(1).max(256),
    adminPassword: z.string().min(1).max(128)
});

export type TenantCreateDtoZodType = z.infer<typeof zTenantCreateDto>;

export const zTenantDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    id: z.optional(z.uuid()),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type TenantDtoZodType = z.infer<typeof zTenantDto>;

export const zPagedResultDto_TenantDto_ = z.object({
    items: z.optional(z.union([
        z.array(zTenantDto),
        z.null()
    ])),
    totalCount: z.optional(z.coerce.bigint())
});

export type PagedResultDto_TenantDto_ZodType = z.infer<typeof zPagedResultDto_TenantDto_>;

export const zTenantUpdateDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    name: z.string().min(0).max(64),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type TenantUpdateDtoZodType = z.infer<typeof zTenantUpdateDto>;

export const zTypeApiDescriptionModel = z.object({
    baseType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isEnum: z.optional(z.boolean()),
    enumNames: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    enumValues: z.optional(z.union([
        z.array(z.unknown()),
        z.null()
    ])),
    genericArguments: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    properties: z.optional(z.union([
        z.array(zPropertyApiDescriptionModel),
        z.null()
    ]))
});

export type TypeApiDescriptionModelZodType = z.infer<typeof zTypeApiDescriptionModel>;

export const zApplicationApiDescriptionModel = z.object({
    modules: z.optional(z.union([
        z.record(z.string(), zModuleApiDescriptionModel),
        z.null()
    ])),
    types: z.optional(z.union([
        z.record(z.string(), zTypeApiDescriptionModel),
        z.null()
    ]))
});

export type ApplicationApiDescriptionModelZodType = z.infer<typeof zApplicationApiDescriptionModel>;

export const zUpdateEmailSettingsDto = z.object({
    smtpHost: z.optional(z.union([
        z.string().max(256),
        z.null()
    ])),
    smtpPort: z.optional(z.int().gte(1).lte(65535)),
    smtpUserName: z.optional(z.union([
        z.string().max(1024),
        z.null()
    ])),
    smtpPassword: z.optional(z.union([
        z.string().max(1024),
        z.null()
    ])),
    smtpDomain: z.optional(z.union([
        z.string().max(1024),
        z.null()
    ])),
    smtpEnableSsl: z.optional(z.boolean()),
    smtpUseDefaultCredentials: z.optional(z.boolean()),
    defaultFromAddress: z.string().min(1).max(1024),
    defaultFromDisplayName: z.string().min(1).max(1024)
});

export type UpdateEmailSettingsDtoZodType = z.infer<typeof zUpdateEmailSettingsDto>;

export const zUpdateFeatureDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    value: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type UpdateFeatureDtoZodType = z.infer<typeof zUpdateFeatureDto>;

export const zUpdateFeaturesDto = z.object({
    features: z.optional(z.union([
        z.array(zUpdateFeatureDto),
        z.null()
    ]))
});

export type UpdateFeaturesDtoZodType = z.infer<typeof zUpdateFeaturesDto>;

export const zUpdatePageInputDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    title: z.string().min(1).max(256),
    slug: z.string().min(1).max(256),
    layoutName: z.optional(z.union([
        z.string().max(256),
        z.null()
    ])),
    content: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    script: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    style: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type UpdatePageInputDtoZodType = z.infer<typeof zUpdatePageInputDto>;

export const zUpdatePermissionDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isGranted: z.optional(z.boolean())
});

export type UpdatePermissionDtoZodType = z.infer<typeof zUpdatePermissionDto>;

export const zUpdatePermissionsDto = z.object({
    permissions: z.optional(z.union([
        z.array(zUpdatePermissionDto),
        z.null()
    ]))
});

export type UpdatePermissionsDtoZodType = z.infer<typeof zUpdatePermissionsDto>;

export const zUpdateProfileDto = z.object({
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly()),
    userName: z.optional(z.union([
        z.string().min(0).max(256),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string().min(0).max(256),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    phoneNumber: z.optional(z.union([
        z.string().min(0).max(16),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type UpdateProfileDtoZodType = z.infer<typeof zUpdateProfileDto>;

export const zUserData = z.object({
    id: z.optional(z.uuid()),
    tenantId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    userName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isActive: z.optional(z.boolean()),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    emailConfirmed: z.optional(z.boolean()),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phoneNumberConfirmed: z.optional(z.boolean()),
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()).readonly(),
        z.null()
    ]).readonly())
});

export type UserDataZodType = z.infer<typeof zUserData>;

export const zListResultDto_userData_ = z.object({
    items: z.optional(z.union([
        z.array(zUserData),
        z.null()
    ]))
});

export type ListResultDto_userData_ZodType = z.infer<typeof zListResultDto_userData_>;

export const zUserLoginInfo = z.object({
    userNameOrEmailAddress: z.string().min(0).max(255),
    password: z.string().min(0).max(32),
    rememberMe: z.optional(z.boolean())
});

export type UserLoginInfoZodType = z.infer<typeof zUserLoginInfo>;

export const zVerifyPasswordResetTokenInput = z.object({
    userId: z.optional(z.uuid()),
    resetToken: z.string().min(1)
});

export type VerifyPasswordResetTokenInputZodType = z.infer<typeof zVerifyPasswordResetTokenInput>;

export const zWindowsTimeZone = z.object({
    timeZoneId: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type WindowsTimeZoneZodType = z.infer<typeof zWindowsTimeZone>;

export const zTimeZone = z.object({
    iana: z.optional(zIanaTimeZone),
    windows: z.optional(zWindowsTimeZone)
});

export type TimeZoneZodType = z.infer<typeof zTimeZone>;

export const zTimingDto = z.object({
    timeZone: z.optional(zTimeZone)
});

export type TimingDtoZodType = z.infer<typeof zTimingDto>;

export const zApplicationConfigurationDto = z.object({
    localization: z.optional(zApplicationLocalizationConfigurationDto),
    auth: z.optional(zApplicationAuthConfigurationDto),
    setting: z.optional(zApplicationSettingConfigurationDto),
    currentUser: z.optional(zCurrentUserDto),
    features: z.optional(zApplicationFeatureConfigurationDto),
    globalFeatures: z.optional(zApplicationGlobalFeatureConfigurationDto),
    multiTenancy: z.optional(zMultiTenancyInfoDto),
    currentTenant: z.optional(zCurrentTenantDto),
    timing: z.optional(zTimingDto),
    clock: z.optional(zClockDto),
    objectExtensions: z.optional(zObjectExtensionsDto),
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ]))
});

export type ApplicationConfigurationDtoZodType = z.infer<typeof zApplicationConfigurationDto>;

export const zAbpLoginResultWritable = z.object({
    result: z.optional(zLoginResultType)
});

export type AbpLoginResultWritableZodType = z.infer<typeof zAbpLoginResultWritable>;

export const zCmsKitPageDtoWritable = z.object({
    id: z.optional(z.uuid()),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    slug: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    layoutName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    content: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    script: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    style: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type CmsKitPageDtoWritableZodType = z.infer<typeof zCmsKitPageDtoWritable>;

export const zCreatePageInputDtoWritable = z.object({
    title: z.string().min(1).max(256),
    slug: z.string().min(1).max(256),
    layoutName: z.optional(z.union([
        z.string().max(256),
        z.null()
    ])),
    content: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    script: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    style: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ]))
});

export type CreatePageInputDtoWritableZodType = z.infer<typeof zCreatePageInputDtoWritable>;

export const zIValueValidatorWritable = z.record(z.string(), z.never());

export type IValueValidatorWritableZodType = z.infer<typeof zIValueValidatorWritable>;

export const zIStringValueTypeWritable = z.object({
    validator: z.optional(zIValueValidatorWritable)
});

export type IStringValueTypeWritableZodType = z.infer<typeof zIStringValueTypeWritable>;

export const zFeatureDtoWritable = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    value: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    provider: z.optional(zFeatureProviderDto),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    valueType: z.optional(zIStringValueTypeWritable),
    depth: z.optional(z.int()),
    parentName: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type FeatureDtoWritableZodType = z.infer<typeof zFeatureDtoWritable>;

export const zFeatureGroupDtoWritable = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    features: z.optional(z.union([
        z.array(zFeatureDtoWritable),
        z.null()
    ]))
});

export type FeatureGroupDtoWritableZodType = z.infer<typeof zFeatureGroupDtoWritable>;

export const zGetFeatureListResultDtoWritable = z.object({
    groups: z.optional(z.union([
        z.array(zFeatureGroupDtoWritable),
        z.null()
    ]))
});

export type GetFeatureListResultDtoWritableZodType = z.infer<typeof zGetFeatureListResultDtoWritable>;

export const zIdentityRoleCreateDtoWritable = z.object({
    name: z.string().min(0).max(256),
    isDefault: z.optional(z.boolean()),
    isPublic: z.optional(z.boolean())
});

export type IdentityRoleCreateDtoWritableZodType = z.infer<typeof zIdentityRoleCreateDtoWritable>;

export const zIdentityRoleDtoWritable = z.object({
    id: z.optional(z.uuid()),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isDefault: z.optional(z.boolean()),
    isStatic: z.optional(z.boolean()),
    isPublic: z.optional(z.boolean()),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    creationTime: z.optional(z.iso.datetime())
});

export type IdentityRoleDtoWritableZodType = z.infer<typeof zIdentityRoleDtoWritable>;

export const zIdentityRoleUpdateDtoWritable = z.object({
    name: z.string().min(0).max(256),
    isDefault: z.optional(z.boolean()),
    isPublic: z.optional(z.boolean()),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type IdentityRoleUpdateDtoWritableZodType = z.infer<typeof zIdentityRoleUpdateDtoWritable>;

export const zIdentityUserCreateDtoWritable = z.object({
    userName: z.string().min(0).max(256),
    name: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    email: z.email().min(0).max(256),
    phoneNumber: z.optional(z.union([
        z.string().min(0).max(16),
        z.null()
    ])),
    isActive: z.optional(z.boolean()),
    lockoutEnabled: z.optional(z.boolean()),
    roleNames: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    password: z.string().min(0).max(128)
});

export type IdentityUserCreateDtoWritableZodType = z.infer<typeof zIdentityUserCreateDtoWritable>;

export const zIdentityUserDtoWritable = z.object({
    id: z.optional(z.uuid()),
    creationTime: z.optional(z.iso.datetime()),
    creatorId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    lastModificationTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    lastModifierId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    isDeleted: z.optional(z.boolean()),
    deleterId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    deletionTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    tenantId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    userName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    emailConfirmed: z.optional(z.boolean()),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phoneNumberConfirmed: z.optional(z.boolean()),
    isActive: z.optional(z.boolean()),
    lockoutEnabled: z.optional(z.boolean()),
    accessFailedCount: z.optional(z.int()),
    lockoutEnd: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    entityVersion: z.optional(z.int()),
    lastPasswordChangeTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
});

export type IdentityUserDtoWritableZodType = z.infer<typeof zIdentityUserDtoWritable>;

export const zIdentityUserUpdateDtoWritable = z.object({
    userName: z.string().min(0).max(256),
    name: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    email: z.email().min(0).max(256),
    phoneNumber: z.optional(z.union([
        z.string().min(0).max(16),
        z.null()
    ])),
    isActive: z.optional(z.boolean()),
    lockoutEnabled: z.optional(z.boolean()),
    roleNames: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    password: z.optional(z.union([
        z.string().min(0).max(128),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type IdentityUserUpdateDtoWritableZodType = z.infer<typeof zIdentityUserUpdateDtoWritable>;

export const zLanguageInfoWritable = z.object({
    cultureName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    uiCultureName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    displayName: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type LanguageInfoWritableZodType = z.infer<typeof zLanguageInfoWritable>;

export const zApplicationLocalizationConfigurationDtoWritable = z.object({
    values: z.optional(z.union([
        z.record(z.string(), z.record(z.string(), z.string())),
        z.null()
    ])),
    resources: z.optional(z.union([
        z.record(z.string(), zApplicationLocalizationResourceDto),
        z.null()
    ])),
    languages: z.optional(z.union([
        z.array(zLanguageInfoWritable),
        z.null()
    ])),
    currentCulture: z.optional(zCurrentCultureDto),
    defaultResourceName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    languagesMap: z.optional(z.union([
        z.record(z.string(), z.array(zNameValue)),
        z.null()
    ])),
    languageFilesMap: z.optional(z.union([
        z.record(z.string(), z.array(zNameValue)),
        z.null()
    ]))
});

export type ApplicationLocalizationConfigurationDtoWritableZodType = z.infer<typeof zApplicationLocalizationConfigurationDtoWritable>;

export const zApplicationConfigurationDtoWritable = z.object({
    localization: z.optional(zApplicationLocalizationConfigurationDtoWritable),
    auth: z.optional(zApplicationAuthConfigurationDto),
    setting: z.optional(zApplicationSettingConfigurationDto),
    currentUser: z.optional(zCurrentUserDto),
    features: z.optional(zApplicationFeatureConfigurationDto),
    globalFeatures: z.optional(zApplicationGlobalFeatureConfigurationDto),
    multiTenancy: z.optional(zMultiTenancyInfoDto),
    currentTenant: z.optional(zCurrentTenantDto),
    timing: z.optional(zTimingDto),
    clock: z.optional(zClockDto),
    objectExtensions: z.optional(zObjectExtensionsDto),
    extraProperties: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ]))
});

export type ApplicationConfigurationDtoWritableZodType = z.infer<typeof zApplicationConfigurationDtoWritable>;

export const zListResultDto_IdentityRoleDto_Writable = z.object({
    items: z.optional(z.union([
        z.array(zIdentityRoleDtoWritable),
        z.null()
    ]))
});

export type ListResultDto_IdentityRoleDto_WritableZodType = z.infer<typeof zListResultDto_IdentityRoleDto_Writable>;

export const zPageDtoWritable = z.object({
    id: z.optional(z.uuid()),
    creationTime: z.optional(z.iso.datetime()),
    creatorId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    lastModificationTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    lastModifierId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    title: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    slug: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    layoutName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    content: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    script: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    style: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isHomePage: z.optional(z.boolean()),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type PageDtoWritableZodType = z.infer<typeof zPageDtoWritable>;

export const zPagedResultDto_IdentityRoleDto_Writable = z.object({
    items: z.optional(z.union([
        z.array(zIdentityRoleDtoWritable),
        z.null()
    ])),
    totalCount: z.optional(z.coerce.bigint())
});

export type PagedResultDto_IdentityRoleDto_WritableZodType = z.infer<typeof zPagedResultDto_IdentityRoleDto_Writable>;

export const zPagedResultDto_IdentityUserDto_Writable = z.object({
    items: z.optional(z.union([
        z.array(zIdentityUserDtoWritable),
        z.null()
    ])),
    totalCount: z.optional(z.coerce.bigint())
});

export type PagedResultDto_IdentityUserDto_WritableZodType = z.infer<typeof zPagedResultDto_IdentityUserDto_Writable>;

export const zPagedResultDto_PageDto_Writable = z.object({
    items: z.optional(z.union([
        z.array(zPageDtoWritable),
        z.null()
    ])),
    totalCount: z.optional(z.coerce.bigint())
});

export type PagedResultDto_PageDto_WritableZodType = z.infer<typeof zPagedResultDto_PageDto_Writable>;

export const zProfileDtoWritable = z.object({
    userName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isExternal: z.optional(z.boolean()),
    hasPassword: z.optional(z.boolean()),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type ProfileDtoWritableZodType = z.infer<typeof zProfileDtoWritable>;

export const zRegisterDtoWritable = z.object({
    userName: z.string().min(0).max(256),
    emailAddress: z.email().min(0).max(256),
    password: z.string().min(0).max(128),
    appName: z.string().min(1)
});

export type RegisterDtoWritableZodType = z.infer<typeof zRegisterDtoWritable>;

export const zTenantCreateDtoWritable = z.object({
    name: z.string().min(0).max(64),
    adminEmailAddress: z.email().min(1).max(256),
    adminPassword: z.string().min(1).max(128)
});

export type TenantCreateDtoWritableZodType = z.infer<typeof zTenantCreateDtoWritable>;

export const zTenantDtoWritable = z.object({
    id: z.optional(z.uuid()),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type TenantDtoWritableZodType = z.infer<typeof zTenantDtoWritable>;

export const zPagedResultDto_TenantDto_Writable = z.object({
    items: z.optional(z.union([
        z.array(zTenantDtoWritable),
        z.null()
    ])),
    totalCount: z.optional(z.coerce.bigint())
});

export type PagedResultDto_TenantDto_WritableZodType = z.infer<typeof zPagedResultDto_TenantDto_Writable>;

export const zTenantUpdateDtoWritable = z.object({
    name: z.string().min(0).max(64),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type TenantUpdateDtoWritableZodType = z.infer<typeof zTenantUpdateDtoWritable>;

export const zUpdatePageInputDtoWritable = z.object({
    title: z.string().min(1).max(256),
    slug: z.string().min(1).max(256),
    layoutName: z.optional(z.union([
        z.string().max(256),
        z.null()
    ])),
    content: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    script: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    style: z.optional(z.union([
        z.string().max(2147483647),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type UpdatePageInputDtoWritableZodType = z.infer<typeof zUpdatePageInputDtoWritable>;

export const zUpdateProfileDtoWritable = z.object({
    userName: z.optional(z.union([
        z.string().min(0).max(256),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string().min(0).max(256),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string().min(0).max(64),
        z.null()
    ])),
    phoneNumber: z.optional(z.union([
        z.string().min(0).max(16),
        z.null()
    ])),
    concurrencyStamp: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type UpdateProfileDtoWritableZodType = z.infer<typeof zUpdateProfileDtoWritable>;

export const zUserDataWritable = z.object({
    id: z.optional(z.uuid()),
    tenantId: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    userName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isActive: z.optional(z.boolean()),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    emailConfirmed: z.optional(z.boolean()),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phoneNumberConfirmed: z.optional(z.boolean())
});

export type UserDataWritableZodType = z.infer<typeof zUserDataWritable>;

export const zListResultDto_userData_Writable = z.object({
    items: z.optional(z.union([
        z.array(zUserDataWritable),
        z.null()
    ]))
});

export type ListResultDto_userData_WritableZodType = z.infer<typeof zListResultDto_userData_Writable>;

export const zGetApiAbpApiDefinitionData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        IncludeTypes: z.optional(z.boolean())
    }))
});

export type GetApiAbpApiDefinitionDataZodType = z.infer<typeof zGetApiAbpApiDefinitionData>;

/**
 * OK
 */
export const zGetApiAbpApiDefinitionResponse = zApplicationApiDescriptionModel;

export type GetApiAbpApiDefinitionResponseZodType = z.infer<typeof zGetApiAbpApiDefinitionResponse>;

export const zGetApiAbpApplicationConfigurationData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        IncludeLocalizationResources: z.optional(z.boolean())
    }))
});

export type GetApiAbpApplicationConfigurationDataZodType = z.infer<typeof zGetApiAbpApplicationConfigurationData>;

/**
 * OK
 */
export const zGetApiAbpApplicationConfigurationResponse = zApplicationConfigurationDto;

export type GetApiAbpApplicationConfigurationResponseZodType = z.infer<typeof zGetApiAbpApplicationConfigurationResponse>;

export const zGetApiAbpApplicationLocalizationData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        CultureName: z.string(),
        OnlyDynamics: z.optional(z.boolean())
    })
});

export type GetApiAbpApplicationLocalizationDataZodType = z.infer<typeof zGetApiAbpApplicationLocalizationData>;

/**
 * OK
 */
export const zGetApiAbpApplicationLocalizationResponse = zApplicationLocalizationDto;

export type GetApiAbpApplicationLocalizationResponseZodType = z.infer<typeof zGetApiAbpApplicationLocalizationResponse>;

export const zGetApiAbpMultiTenancyTenantsByNameByNameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        name: z.string()
    }),
    query: z.optional(z.never())
});

export type GetApiAbpMultiTenancyTenantsByNameByNameDataZodType = z.infer<typeof zGetApiAbpMultiTenancyTenantsByNameByNameData>;

/**
 * OK
 */
export const zGetApiAbpMultiTenancyTenantsByNameByNameResponse = zFindTenantResultDto;

export type GetApiAbpMultiTenancyTenantsByNameByNameResponseZodType = z.infer<typeof zGetApiAbpMultiTenancyTenantsByNameByNameResponse>;

export const zGetApiAbpMultiTenancyTenantsByIdByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type GetApiAbpMultiTenancyTenantsByIdByIdDataZodType = z.infer<typeof zGetApiAbpMultiTenancyTenantsByIdByIdData>;

/**
 * OK
 */
export const zGetApiAbpMultiTenancyTenantsByIdByIdResponse = zFindTenantResultDto;

export type GetApiAbpMultiTenancyTenantsByIdByIdResponseZodType = z.infer<typeof zGetApiAbpMultiTenancyTenantsByIdByIdResponse>;

export const zPostApiAccountRegisterData = z.object({
    body: z.optional(zRegisterDtoWritable),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiAccountRegisterDataZodType = z.infer<typeof zPostApiAccountRegisterData>;

/**
 * OK
 */
export const zPostApiAccountRegisterResponse = zIdentityUserDto;

export type PostApiAccountRegisterResponseZodType = z.infer<typeof zPostApiAccountRegisterResponse>;

export const zPostApiAccountSendPasswordResetCodeData = z.object({
    body: z.optional(zSendPasswordResetCodeDto),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiAccountSendPasswordResetCodeDataZodType = z.infer<typeof zPostApiAccountSendPasswordResetCodeData>;

export const zPostApiAccountVerifyPasswordResetTokenData = z.object({
    body: z.optional(zVerifyPasswordResetTokenInput),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiAccountVerifyPasswordResetTokenDataZodType = z.infer<typeof zPostApiAccountVerifyPasswordResetTokenData>;

/**
 * OK
 */
export const zPostApiAccountVerifyPasswordResetTokenResponse = z.boolean();

export type PostApiAccountVerifyPasswordResetTokenResponseZodType = z.infer<typeof zPostApiAccountVerifyPasswordResetTokenResponse>;

export const zPostApiAccountResetPasswordData = z.object({
    body: z.optional(zResetPasswordDto),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiAccountResetPasswordDataZodType = z.infer<typeof zPostApiAccountResetPasswordData>;

export const zDeleteApiAppBookByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type DeleteApiAppBookByIdDataZodType = z.infer<typeof zDeleteApiAppBookByIdData>;

export const zGetApiAppBookByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type GetApiAppBookByIdDataZodType = z.infer<typeof zGetApiAppBookByIdData>;

/**
 * OK
 */
export const zGetApiAppBookByIdResponse = zBookDto;

export type GetApiAppBookByIdResponseZodType = z.infer<typeof zGetApiAppBookByIdResponse>;

export const zPutApiAppBookByIdData = z.object({
    body: z.optional(zCreateUpdateBookDto),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type PutApiAppBookByIdDataZodType = z.infer<typeof zPutApiAppBookByIdData>;

/**
 * OK
 */
export const zPutApiAppBookByIdResponse = zBookDto;

export type PutApiAppBookByIdResponseZodType = z.infer<typeof zPutApiAppBookByIdResponse>;

export const zGetApiAppBookData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        Sorting: z.optional(z.string()),
        SkipCount: z.optional(z.int().gte(0).lte(2147483647)),
        MaxResultCount: z.optional(z.int().gte(1).lte(2147483647))
    }))
});

export type GetApiAppBookDataZodType = z.infer<typeof zGetApiAppBookData>;

/**
 * OK
 */
export const zGetApiAppBookResponse = zPagedResultDto_BookDto_;

export type GetApiAppBookResponseZodType = z.infer<typeof zGetApiAppBookResponse>;

export const zPostApiAppBookData = z.object({
    body: z.optional(zCreateUpdateBookDto),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiAppBookDataZodType = z.infer<typeof zPostApiAppBookData>;

/**
 * OK
 */
export const zPostApiAppBookResponse = zBookDto;

export type PostApiAppBookResponseZodType = z.infer<typeof zPostApiAppBookResponse>;

export const zGetCmsKitGlobalResourcesStyleData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetCmsKitGlobalResourcesStyleDataZodType = z.infer<typeof zGetCmsKitGlobalResourcesStyleData>;

export const zGetCmsKitGlobalResourcesScriptData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetCmsKitGlobalResourcesScriptDataZodType = z.infer<typeof zGetCmsKitGlobalResourcesScriptData>;

export const zPostApiAccountDynamicClaimsRefreshData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiAccountDynamicClaimsRefreshDataZodType = z.infer<typeof zPostApiAccountDynamicClaimsRefreshData>;

export const zGetApiSettingManagementEmailingData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiSettingManagementEmailingDataZodType = z.infer<typeof zGetApiSettingManagementEmailingData>;

/**
 * OK
 */
export const zGetApiSettingManagementEmailingResponse = zEmailSettingsDto;

export type GetApiSettingManagementEmailingResponseZodType = z.infer<typeof zGetApiSettingManagementEmailingResponse>;

export const zPostApiSettingManagementEmailingData = z.object({
    body: z.optional(zUpdateEmailSettingsDto),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiSettingManagementEmailingDataZodType = z.infer<typeof zPostApiSettingManagementEmailingData>;

export const zPostApiSettingManagementEmailingSendTestEmailData = z.object({
    body: z.optional(zSendTestEmailInput),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiSettingManagementEmailingSendTestEmailDataZodType = z.infer<typeof zPostApiSettingManagementEmailingSendTestEmailData>;

export const zDeleteApiFeatureManagementFeaturesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        providerName: z.optional(z.string()),
        providerKey: z.optional(z.string())
    }))
});

export type DeleteApiFeatureManagementFeaturesDataZodType = z.infer<typeof zDeleteApiFeatureManagementFeaturesData>;

export const zGetApiFeatureManagementFeaturesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        providerName: z.optional(z.string()),
        providerKey: z.optional(z.string())
    }))
});

export type GetApiFeatureManagementFeaturesDataZodType = z.infer<typeof zGetApiFeatureManagementFeaturesData>;

/**
 * OK
 */
export const zGetApiFeatureManagementFeaturesResponse = zGetFeatureListResultDto;

export type GetApiFeatureManagementFeaturesResponseZodType = z.infer<typeof zGetApiFeatureManagementFeaturesResponse>;

export const zPutApiFeatureManagementFeaturesData = z.object({
    body: z.optional(zUpdateFeaturesDto),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        providerName: z.optional(z.string()),
        providerKey: z.optional(z.string())
    }))
});

export type PutApiFeatureManagementFeaturesDataZodType = z.infer<typeof zPutApiFeatureManagementFeaturesData>;

export const zPostApiAccountLoginData = z.object({
    body: z.optional(zUserLoginInfo),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiAccountLoginDataZodType = z.infer<typeof zPostApiAccountLoginData>;

/**
 * OK
 */
export const zPostApiAccountLoginResponse = zAbpLoginResult;

export type PostApiAccountLoginResponseZodType = z.infer<typeof zPostApiAccountLoginResponse>;

export const zGetApiAccountLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiAccountLogoutDataZodType = z.infer<typeof zGetApiAccountLogoutData>;

export const zPostApiAccountCheckPasswordData = z.object({
    body: z.optional(zUserLoginInfo),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiAccountCheckPasswordDataZodType = z.infer<typeof zPostApiAccountCheckPasswordData>;

/**
 * OK
 */
export const zPostApiAccountCheckPasswordResponse = zAbpLoginResult;

export type PostApiAccountCheckPasswordResponseZodType = z.infer<typeof zPostApiAccountCheckPasswordResponse>;

export const zDeleteApiCmsKitAdminPagesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type DeleteApiCmsKitAdminPagesByIdDataZodType = z.infer<typeof zDeleteApiCmsKitAdminPagesByIdData>;

export const zGetApiCmsKitAdminPagesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type GetApiCmsKitAdminPagesByIdDataZodType = z.infer<typeof zGetApiCmsKitAdminPagesByIdData>;

/**
 * OK
 */
export const zGetApiCmsKitAdminPagesByIdResponse = zPageDto;

export type GetApiCmsKitAdminPagesByIdResponseZodType = z.infer<typeof zGetApiCmsKitAdminPagesByIdResponse>;

export const zPutApiCmsKitAdminPagesByIdData = z.object({
    body: z.optional(zUpdatePageInputDtoWritable),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type PutApiCmsKitAdminPagesByIdDataZodType = z.infer<typeof zPutApiCmsKitAdminPagesByIdData>;

/**
 * OK
 */
export const zPutApiCmsKitAdminPagesByIdResponse = zPageDto;

export type PutApiCmsKitAdminPagesByIdResponseZodType = z.infer<typeof zPutApiCmsKitAdminPagesByIdResponse>;

export const zGetApiCmsKitAdminPagesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        Filter: z.optional(z.string()),
        Sorting: z.optional(z.string()),
        SkipCount: z.optional(z.int().gte(0).lte(2147483647)),
        MaxResultCount: z.optional(z.int().gte(1).lte(2147483647))
    }))
});

export type GetApiCmsKitAdminPagesDataZodType = z.infer<typeof zGetApiCmsKitAdminPagesData>;

/**
 * OK
 */
export const zGetApiCmsKitAdminPagesResponse = zPagedResultDto_PageDto_;

export type GetApiCmsKitAdminPagesResponseZodType = z.infer<typeof zGetApiCmsKitAdminPagesResponse>;

export const zPostApiCmsKitAdminPagesData = z.object({
    body: z.optional(zCreatePageInputDtoWritable),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiCmsKitAdminPagesDataZodType = z.infer<typeof zPostApiCmsKitAdminPagesData>;

/**
 * OK
 */
export const zPostApiCmsKitAdminPagesResponse = zPageDto;

export type PostApiCmsKitAdminPagesResponseZodType = z.infer<typeof zPostApiCmsKitAdminPagesResponse>;

export const zPutApiCmsKitAdminPagesSetashomepageByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type PutApiCmsKitAdminPagesSetashomepageByIdDataZodType = z.infer<typeof zPutApiCmsKitAdminPagesSetashomepageByIdData>;

export const zGetApiCmsKitPublicPagesBySlugData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        slug: z.optional(z.string())
    }))
});

export type GetApiCmsKitPublicPagesBySlugDataZodType = z.infer<typeof zGetApiCmsKitPublicPagesBySlugData>;

/**
 * OK
 */
export const zGetApiCmsKitPublicPagesBySlugResponse = zCmsKitPageDto;

export type GetApiCmsKitPublicPagesBySlugResponseZodType = z.infer<typeof zGetApiCmsKitPublicPagesBySlugResponse>;

export const zGetApiCmsKitPublicPagesHomeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiCmsKitPublicPagesHomeDataZodType = z.infer<typeof zGetApiCmsKitPublicPagesHomeData>;

/**
 * OK
 */
export const zGetApiCmsKitPublicPagesHomeResponse = zCmsKitPageDto;

export type GetApiCmsKitPublicPagesHomeResponseZodType = z.infer<typeof zGetApiCmsKitPublicPagesHomeResponse>;

export const zGetApiCmsKitPublicPagesExistData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        slug: z.optional(z.string())
    }))
});

export type GetApiCmsKitPublicPagesExistDataZodType = z.infer<typeof zGetApiCmsKitPublicPagesExistData>;

/**
 * OK
 */
export const zGetApiCmsKitPublicPagesExistResponse = z.boolean();

export type GetApiCmsKitPublicPagesExistResponseZodType = z.infer<typeof zGetApiCmsKitPublicPagesExistResponse>;

export const zGetApiPermissionManagementPermissionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        providerName: z.optional(z.string()),
        providerKey: z.optional(z.string())
    }))
});

export type GetApiPermissionManagementPermissionsDataZodType = z.infer<typeof zGetApiPermissionManagementPermissionsData>;

/**
 * OK
 */
export const zGetApiPermissionManagementPermissionsResponse = zGetPermissionListResultDto;

export type GetApiPermissionManagementPermissionsResponseZodType = z.infer<typeof zGetApiPermissionManagementPermissionsResponse>;

export const zPutApiPermissionManagementPermissionsData = z.object({
    body: z.optional(zUpdatePermissionsDto),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        providerName: z.optional(z.string()),
        providerKey: z.optional(z.string())
    }))
});

export type PutApiPermissionManagementPermissionsDataZodType = z.infer<typeof zPutApiPermissionManagementPermissionsData>;

export const zGetApiPermissionManagementPermissionsByGroupData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        groupName: z.optional(z.string()),
        providerName: z.optional(z.string()),
        providerKey: z.optional(z.string())
    }))
});

export type GetApiPermissionManagementPermissionsByGroupDataZodType = z.infer<typeof zGetApiPermissionManagementPermissionsByGroupData>;

/**
 * OK
 */
export const zGetApiPermissionManagementPermissionsByGroupResponse = zGetPermissionListResultDto;

export type GetApiPermissionManagementPermissionsByGroupResponseZodType = z.infer<typeof zGetApiPermissionManagementPermissionsByGroupResponse>;

export const zGetApiAccountMyProfileData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiAccountMyProfileDataZodType = z.infer<typeof zGetApiAccountMyProfileData>;

/**
 * OK
 */
export const zGetApiAccountMyProfileResponse = zProfileDto;

export type GetApiAccountMyProfileResponseZodType = z.infer<typeof zGetApiAccountMyProfileResponse>;

export const zPutApiAccountMyProfileData = z.object({
    body: z.optional(zUpdateProfileDtoWritable),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PutApiAccountMyProfileDataZodType = z.infer<typeof zPutApiAccountMyProfileData>;

/**
 * OK
 */
export const zPutApiAccountMyProfileResponse = zProfileDto;

export type PutApiAccountMyProfileResponseZodType = z.infer<typeof zPutApiAccountMyProfileResponse>;

export const zPostApiAccountMyProfileChangePasswordData = z.object({
    body: z.optional(zChangePasswordInput),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiAccountMyProfileChangePasswordDataZodType = z.infer<typeof zPostApiAccountMyProfileChangePasswordData>;

export const zGetApiIdentityRolesAllData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiIdentityRolesAllDataZodType = z.infer<typeof zGetApiIdentityRolesAllData>;

/**
 * OK
 */
export const zGetApiIdentityRolesAllResponse = zListResultDto_IdentityRoleDto_;

export type GetApiIdentityRolesAllResponseZodType = z.infer<typeof zGetApiIdentityRolesAllResponse>;

export const zGetApiIdentityRolesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        Filter: z.optional(z.string()),
        Sorting: z.optional(z.string()),
        SkipCount: z.optional(z.int().gte(0).lte(2147483647)),
        MaxResultCount: z.optional(z.int().gte(1).lte(2147483647)),
        ExtraProperties: z.optional(z.record(z.string(), z.unknown()))
    }))
});

export type GetApiIdentityRolesDataZodType = z.infer<typeof zGetApiIdentityRolesData>;

/**
 * OK
 */
export const zGetApiIdentityRolesResponse = zPagedResultDto_IdentityRoleDto_;

export type GetApiIdentityRolesResponseZodType = z.infer<typeof zGetApiIdentityRolesResponse>;

export const zPostApiIdentityRolesData = z.object({
    body: z.optional(zIdentityRoleCreateDtoWritable),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiIdentityRolesDataZodType = z.infer<typeof zPostApiIdentityRolesData>;

/**
 * OK
 */
export const zPostApiIdentityRolesResponse = zIdentityRoleDto;

export type PostApiIdentityRolesResponseZodType = z.infer<typeof zPostApiIdentityRolesResponse>;

export const zDeleteApiIdentityRolesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type DeleteApiIdentityRolesByIdDataZodType = z.infer<typeof zDeleteApiIdentityRolesByIdData>;

export const zGetApiIdentityRolesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type GetApiIdentityRolesByIdDataZodType = z.infer<typeof zGetApiIdentityRolesByIdData>;

/**
 * OK
 */
export const zGetApiIdentityRolesByIdResponse = zIdentityRoleDto;

export type GetApiIdentityRolesByIdResponseZodType = z.infer<typeof zGetApiIdentityRolesByIdResponse>;

export const zPutApiIdentityRolesByIdData = z.object({
    body: z.optional(zIdentityRoleUpdateDtoWritable),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type PutApiIdentityRolesByIdDataZodType = z.infer<typeof zPutApiIdentityRolesByIdData>;

/**
 * OK
 */
export const zPutApiIdentityRolesByIdResponse = zIdentityRoleDto;

export type PutApiIdentityRolesByIdResponseZodType = z.infer<typeof zPutApiIdentityRolesByIdResponse>;

export const zDeleteApiMultiTenancyTenantsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type DeleteApiMultiTenancyTenantsByIdDataZodType = z.infer<typeof zDeleteApiMultiTenancyTenantsByIdData>;

export const zGetApiMultiTenancyTenantsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type GetApiMultiTenancyTenantsByIdDataZodType = z.infer<typeof zGetApiMultiTenancyTenantsByIdData>;

/**
 * OK
 */
export const zGetApiMultiTenancyTenantsByIdResponse = zTenantDto;

export type GetApiMultiTenancyTenantsByIdResponseZodType = z.infer<typeof zGetApiMultiTenancyTenantsByIdResponse>;

export const zPutApiMultiTenancyTenantsByIdData = z.object({
    body: z.optional(zTenantUpdateDtoWritable),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type PutApiMultiTenancyTenantsByIdDataZodType = z.infer<typeof zPutApiMultiTenancyTenantsByIdData>;

/**
 * OK
 */
export const zPutApiMultiTenancyTenantsByIdResponse = zTenantDto;

export type PutApiMultiTenancyTenantsByIdResponseZodType = z.infer<typeof zPutApiMultiTenancyTenantsByIdResponse>;

export const zGetApiMultiTenancyTenantsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        Filter: z.optional(z.string()),
        Sorting: z.optional(z.string()),
        SkipCount: z.optional(z.int().gte(0).lte(2147483647)),
        MaxResultCount: z.optional(z.int().gte(1).lte(2147483647))
    }))
});

export type GetApiMultiTenancyTenantsDataZodType = z.infer<typeof zGetApiMultiTenancyTenantsData>;

/**
 * OK
 */
export const zGetApiMultiTenancyTenantsResponse = zPagedResultDto_TenantDto_;

export type GetApiMultiTenancyTenantsResponseZodType = z.infer<typeof zGetApiMultiTenancyTenantsResponse>;

export const zPostApiMultiTenancyTenantsData = z.object({
    body: z.optional(zTenantCreateDtoWritable),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiMultiTenancyTenantsDataZodType = z.infer<typeof zPostApiMultiTenancyTenantsData>;

/**
 * OK
 */
export const zPostApiMultiTenancyTenantsResponse = zTenantDto;

export type PostApiMultiTenancyTenantsResponseZodType = z.infer<typeof zPostApiMultiTenancyTenantsResponse>;

export const zDeleteApiMultiTenancyTenantsByIdDefaultConnectionStringData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringDataZodType = z.infer<typeof zDeleteApiMultiTenancyTenantsByIdDefaultConnectionStringData>;

export const zGetApiMultiTenancyTenantsByIdDefaultConnectionStringData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringDataZodType = z.infer<typeof zGetApiMultiTenancyTenantsByIdDefaultConnectionStringData>;

/**
 * OK
 */
export const zGetApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = z.string();

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringResponseZodType = z.infer<typeof zGetApiMultiTenancyTenantsByIdDefaultConnectionStringResponse>;

export const zPutApiMultiTenancyTenantsByIdDefaultConnectionStringData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.object({
        defaultConnectionString: z.optional(z.string())
    }))
});

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringDataZodType = z.infer<typeof zPutApiMultiTenancyTenantsByIdDefaultConnectionStringData>;

export const zGetApiSettingManagementTimezoneData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiSettingManagementTimezoneDataZodType = z.infer<typeof zGetApiSettingManagementTimezoneData>;

/**
 * OK
 */
export const zGetApiSettingManagementTimezoneResponse = z.string();

export type GetApiSettingManagementTimezoneResponseZodType = z.infer<typeof zGetApiSettingManagementTimezoneResponse>;

export const zPostApiSettingManagementTimezoneData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        timezone: z.optional(z.string())
    }))
});

export type PostApiSettingManagementTimezoneDataZodType = z.infer<typeof zPostApiSettingManagementTimezoneData>;

export const zGetApiSettingManagementTimezoneTimezonesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiSettingManagementTimezoneTimezonesDataZodType = z.infer<typeof zGetApiSettingManagementTimezoneTimezonesData>;

/**
 * OK
 */
export const zGetApiSettingManagementTimezoneTimezonesResponse = z.array(zNameValue);

export type GetApiSettingManagementTimezoneTimezonesResponseZodType = z.infer<typeof zGetApiSettingManagementTimezoneTimezonesResponse>;

export const zDeleteApiIdentityUsersByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type DeleteApiIdentityUsersByIdDataZodType = z.infer<typeof zDeleteApiIdentityUsersByIdData>;

export const zGetApiIdentityUsersByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type GetApiIdentityUsersByIdDataZodType = z.infer<typeof zGetApiIdentityUsersByIdData>;

/**
 * OK
 */
export const zGetApiIdentityUsersByIdResponse = zIdentityUserDto;

export type GetApiIdentityUsersByIdResponseZodType = z.infer<typeof zGetApiIdentityUsersByIdResponse>;

export const zPutApiIdentityUsersByIdData = z.object({
    body: z.optional(zIdentityUserUpdateDtoWritable),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type PutApiIdentityUsersByIdDataZodType = z.infer<typeof zPutApiIdentityUsersByIdData>;

/**
 * OK
 */
export const zPutApiIdentityUsersByIdResponse = zIdentityUserDto;

export type PutApiIdentityUsersByIdResponseZodType = z.infer<typeof zPutApiIdentityUsersByIdResponse>;

export const zGetApiIdentityUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        Filter: z.optional(z.string()),
        Sorting: z.optional(z.string()),
        SkipCount: z.optional(z.int().gte(0).lte(2147483647)),
        MaxResultCount: z.optional(z.int().gte(1).lte(2147483647)),
        ExtraProperties: z.optional(z.record(z.string(), z.unknown()))
    }))
});

export type GetApiIdentityUsersDataZodType = z.infer<typeof zGetApiIdentityUsersData>;

/**
 * OK
 */
export const zGetApiIdentityUsersResponse = zPagedResultDto_IdentityUserDto_;

export type GetApiIdentityUsersResponseZodType = z.infer<typeof zGetApiIdentityUsersResponse>;

export const zPostApiIdentityUsersData = z.object({
    body: z.optional(zIdentityUserCreateDtoWritable),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type PostApiIdentityUsersDataZodType = z.infer<typeof zPostApiIdentityUsersData>;

/**
 * OK
 */
export const zPostApiIdentityUsersResponse = zIdentityUserDto;

export type PostApiIdentityUsersResponseZodType = z.infer<typeof zPostApiIdentityUsersResponse>;

export const zGetApiIdentityUsersByIdRolesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type GetApiIdentityUsersByIdRolesDataZodType = z.infer<typeof zGetApiIdentityUsersByIdRolesData>;

/**
 * OK
 */
export const zGetApiIdentityUsersByIdRolesResponse = zListResultDto_IdentityRoleDto_;

export type GetApiIdentityUsersByIdRolesResponseZodType = z.infer<typeof zGetApiIdentityUsersByIdRolesResponse>;

export const zPutApiIdentityUsersByIdRolesData = z.object({
    body: z.optional(zIdentityUserUpdateRolesDto),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type PutApiIdentityUsersByIdRolesDataZodType = z.infer<typeof zPutApiIdentityUsersByIdRolesData>;

export const zGetApiIdentityUsersAssignableRolesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export type GetApiIdentityUsersAssignableRolesDataZodType = z.infer<typeof zGetApiIdentityUsersAssignableRolesData>;

/**
 * OK
 */
export const zGetApiIdentityUsersAssignableRolesResponse = zListResultDto_IdentityRoleDto_;

export type GetApiIdentityUsersAssignableRolesResponseZodType = z.infer<typeof zGetApiIdentityUsersAssignableRolesResponse>;

export const zGetApiIdentityUsersByUsernameByUserNameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userName: z.string()
    }),
    query: z.optional(z.never())
});

export type GetApiIdentityUsersByUsernameByUserNameDataZodType = z.infer<typeof zGetApiIdentityUsersByUsernameByUserNameData>;

/**
 * OK
 */
export const zGetApiIdentityUsersByUsernameByUserNameResponse = zIdentityUserDto;

export type GetApiIdentityUsersByUsernameByUserNameResponseZodType = z.infer<typeof zGetApiIdentityUsersByUsernameByUserNameResponse>;

export const zGetApiIdentityUsersByEmailByEmailData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        email: z.string()
    }),
    query: z.optional(z.never())
});

export type GetApiIdentityUsersByEmailByEmailDataZodType = z.infer<typeof zGetApiIdentityUsersByEmailByEmailData>;

/**
 * OK
 */
export const zGetApiIdentityUsersByEmailByEmailResponse = zIdentityUserDto;

export type GetApiIdentityUsersByEmailByEmailResponseZodType = z.infer<typeof zGetApiIdentityUsersByEmailByEmailResponse>;

export const zGetApiIdentityUsersLookupByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export type GetApiIdentityUsersLookupByIdDataZodType = z.infer<typeof zGetApiIdentityUsersLookupByIdData>;

/**
 * OK
 */
export const zGetApiIdentityUsersLookupByIdResponse = zUserData;

export type GetApiIdentityUsersLookupByIdResponseZodType = z.infer<typeof zGetApiIdentityUsersLookupByIdResponse>;

export const zGetApiIdentityUsersLookupByUsernameByUserNameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userName: z.string()
    }),
    query: z.optional(z.never())
});

export type GetApiIdentityUsersLookupByUsernameByUserNameDataZodType = z.infer<typeof zGetApiIdentityUsersLookupByUsernameByUserNameData>;

/**
 * OK
 */
export const zGetApiIdentityUsersLookupByUsernameByUserNameResponse = zUserData;

export type GetApiIdentityUsersLookupByUsernameByUserNameResponseZodType = z.infer<typeof zGetApiIdentityUsersLookupByUsernameByUserNameResponse>;

export const zGetApiIdentityUsersLookupSearchData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        Filter: z.optional(z.string()),
        Sorting: z.optional(z.string()),
        SkipCount: z.optional(z.int().gte(0).lte(2147483647)),
        MaxResultCount: z.optional(z.int().gte(1).lte(2147483647)),
        ExtraProperties: z.optional(z.record(z.string(), z.unknown()))
    }))
});

export type GetApiIdentityUsersLookupSearchDataZodType = z.infer<typeof zGetApiIdentityUsersLookupSearchData>;

/**
 * OK
 */
export const zGetApiIdentityUsersLookupSearchResponse = zListResultDto_userData_;

export type GetApiIdentityUsersLookupSearchResponseZodType = z.infer<typeof zGetApiIdentityUsersLookupSearchResponse>;

export const zGetApiIdentityUsersLookupCountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        Filter: z.optional(z.string())
    }))
});

export type GetApiIdentityUsersLookupCountDataZodType = z.infer<typeof zGetApiIdentityUsersLookupCountData>;

/**
 * OK
 */
export const zGetApiIdentityUsersLookupCountResponse = z.coerce.bigint();

export type GetApiIdentityUsersLookupCountResponseZodType = z.infer<typeof zGetApiIdentityUsersLookupCountResponse>;
